const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const js = fs.readFileSync(path.join(root, 'static/js/tuition_collection.js'), 'utf8');
const app = fs.readFileSync(path.join(root, 'static/js/app.js'), 'utf8');
const html = fs.readFileSync(path.join(root, 'templates/index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'static/css/styles.css'), 'utf8');
new Function(js);
assert.match(html, /data-view="tuition-collection"/);
assert.match(app, /STAFF_ONLY_VIEWS = \[[^\n]*'tuition-collection'/);
assert.match(app, /tuitionCollection\.canLeave\(\)/);
assert.match(app, /tuitionCollection\.reset\(\)/);
assert.match(html, /view-tuition-collection" class="workspace-view compact-search-view"/);
assert.match(js, /version !== listVersion/);
assert.match(js, /version !== detailVersion/);
assert.match(js, /if \(saving\) return/);
assert.match(js, /request_id:requestId/);
assert.match(js, /version:c\.version/);
assert.match(js, /counts_as_reminder/);
assert.match(js, /esc\(event\.memo/);
assert.match(js, /실제 메시지 발송이나 자동 입금 확인 기능이 아닙니다/);
assert.match(js, /\/cases\/\$\{c\.id\}\/complete/);
assert.match(js, /payload\.payment_id = Number/);
assert.match(css, /#view-tuition-collection \.table-card \{ min-height:280px/);
assert.match(css, /@media\(max-width:600px\)/);
console.log('납입 관리 UI 구조·권한·오래된 응답·안전 출력 검사 통과');

assert.match(js, /c\.status === 'confirmed'/);
assert.match(js, /\['notice', 'link_sent', 'reminder'\]\.includes\(option\.value\)/);
assert.match(js, /el\('kind'\)\.value = 'note'/);
assert.match(js, /counts_as_reminder: values\.kind === 'link_sent'/);
assert.match(js, /count\.disabled = kind !== 'link_sent'/);
assert.match(js, /저장하지 않은 입력을 버리고 이 기록을 취소할까요/);
assert.match(js, /id="tc-payment-class" name="ClassType" class="form-control" required/);
